### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by krivadna** [edoardottt/pphack#66]
~/go/bin $ ./pphack -u https://edoardottt.github.io/pp-test/
                 __               __
    ____  ____  / /_  ____ ______/ /__
   / __ \/ __ \/ __ \/ __ `/ ___/ //_/
  / /_/ / /_/ / / / / /_/ / /__/ ,<
 / .___/ .___/_/ /_/\__,_/\___/_/|_|
/_/   /_/                             v0.0.2

                @edoardottt, https://www.edoardoottavianelli.it/
                             https://github.com/edoardottt/

[FTL] error starting browser: exec: "google-chrome": executable file not found in $PATH

**Comment by edoardottt** [comment]
pphack relies on [`chromedp`](https://github.com/chromedp/chromedp), so you need a Chrome or Chromium browser.

ref: 
- https://github.com/edoardottt/pphack?tab=readme-ov-file#using-go
- https://github.com/chromedp/chromedp
