### ISSUE TITLE
ERROR: could not retrieve document root

### ISSUE THREAD

**Issue by Teicu** [edoardottt/pphack#77]
Hi, 

Any idea why I'm getting these errors? 

2024/05/23 14:09:59 ERROR: could not retrieve document root for 034CE60B540B2D0B4E82A6B8CE74A5DE: context deadline exceeded
2024/05/23 14:10:09 ERROR: could not retrieve document root for 806BF5A1C0767CD11104F58FFAF2E12B: context deadline exceeded
2024/05/23 14:10:33 ERROR: could not retrieve document root for 8E3E7104E1AEB7E77E93171255163BA6: context deadline exceeded
 

Thank you

**Comment by edoardottt** [comment]
hi @Teicu . It's not easy to solve this issues without context. 
could you please provide the command you executed with the input provided? 
I'll try to reproduce the issue

**Comment by edoardottt** [comment]
Have u managed to solve the error or you need assistance? @Teicu

**Comment by Teicu** [comment]
Hi, 

./pphack -l urls.txt 

<img width="1148" alt="Screenshot 2024-06-05 at 15 20 46" src="https://github.com/edoardottt/pphack/assets/1572822/ce672f4b-ac01-4523-83e9-286a4a8fb31d">

**Comment by edoardottt** [comment]
thanks. 
you should provide me the file `urls.txt` in order to reproduce the issue

**Comment by Teicu** [comment]
I ran ./gau testphp.vulnweb.com, saved the output to a text file, and then executed ./pphack -l urls.txt. This issue occurs with other sites as well, not just this one. I'm using a MacBook M2 Max, though I'm not sure if that's relevant.

**Comment by edoardottt** [comment]
I've used a MacBook M2 as well and it works fine. 
do you have chrome installed on your machine?

**Comment by Teicu** [comment]
Yes of course 

<img width="792" alt="Screenshot 2024-06-05 at 15 37 13" src="https://github.com/edoardottt/pphack/assets/1572822/adde103d-45c1-424d-98c8-aa99a1c0ac11">

**Comment by edoardottt** [comment]
the only thing I find is this https://github.com/chromedp/chromedp/issues/904
try to execute the command suggested or reproduce the bug with the code snippet in the issue.
the only reason of this can be chromedp.
let me know the output you get doing that
